
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVISAO MULTIPLICACAO NUMERO SOMA SUBTRACAOexp : exp SOMA exp1exp : exp SUBTRACAO exp1exp : exp1exp1 : exp1 MULTIPLICACAO exp2exp1 : exp1 DIVISAO exp2exp1 : exp2exp2 : NUMERO'
    
_lr_action_items = {'NUMERO':([0,5,6,7,8,],[4,4,4,4,4,]),'$end':([1,2,3,4,9,10,11,12,],[0,-3,-6,-7,-1,-2,-4,-5,]),'SOMA':([1,2,3,4,9,10,11,12,],[5,-3,-6,-7,-1,-2,-4,-5,]),'SUBTRACAO':([1,2,3,4,9,10,11,12,],[6,-3,-6,-7,-1,-2,-4,-5,]),'MULTIPLICACAO':([2,3,4,9,10,11,12,],[7,-6,-7,7,7,-4,-5,]),'DIVISAO':([2,3,4,9,10,11,12,],[8,-6,-7,8,8,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'exp1':([0,5,6,],[2,9,10,]),'exp2':([0,5,6,7,8,],[3,3,3,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp SOMA exp1','exp',3,'p_exp_soma','calcparser.py',11),
  ('exp -> exp SUBTRACAO exp1','exp',3,'p_exp_subtracao','calcparser.py',14),
  ('exp -> exp1','exp',1,'p_exp_exp1','calcparser.py',17),
  ('exp1 -> exp1 MULTIPLICACAO exp2','exp1',3,'p_exp1_multiplicacao','calcparser.py',20),
  ('exp1 -> exp1 DIVISAO exp2','exp1',3,'p_exp1_divisao','calcparser.py',23),
  ('exp1 -> exp2','exp1',1,'p_exp1_exp2','calcparser.py',26),
  ('exp2 -> NUMERO','exp2',1,'p_exp2_numero','calcparser.py',29),
]
